# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 51231a57d999ed3da138634ddded51b2b0d2c03b57f8bcace4093ceb79ec00c935328d4a2236feefaeb5cfbb5964d9575449866eebc6b5c9b43c0dcbb9d752d1

test:
  secret_key_base: 3266bbab22060a85c86c532a7c362bd5bfe2e0d37d5d4d57e39754cae658278873ff3fbe9e68a6d1bdd6483257c50331ea0c4b7c5c3d25ac0cf7eda766d43b08

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
